version: "3.5"

services:
  poker-api:
    build: .
    ports:
      - target: 80
        published: 80
    networks:
      - backend
      - poker-frontend
    environment:
      - PORT=80

  redis:
    image: redis:alpine
    ports:
      - target: 6379
        published: 6379
    networks:
      - backend

networks:
  backend:
  poker-frontend:
    external: true
