FROM python@sha256:5fae85eea1d49fa7e0b60ab7091922329d1f573a3359f9dc438ac0614169c22a

WORKDIR /usr/src/app
COPY requirements.txt src/ ./

RUN pip install --no-cache-dir -r requirements.txt

ENV REDIS_HOST=redis
ENV REDIS_PORT=6379
ENV PORT=8080

EXPOSE 8080
ENTRYPOINT ["python3", "api.py"]