FROM python@sha256:30fb678d7f0b4265525d58a7be2973c83755c93dda401a0d5979942eeaecd361

WORKDIR /usr/src/app
COPY requirements.txt src/ ./

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONUNBUFFERED=0

ENV REDIS_HOST=redis
ENV REDIS_PORT=6379
ENV PORT=8080

EXPOSE 8080
ENTRYPOINT ["python3", "api.py"]