version: "3.5"

services:
  poker-web:
    image: carlschader/poker-web
    depends_on:
      - poker-api
    ports:
      - target: 80
        published: 80
    environment:
    - PORT=80
    - API_URL=http://poker-api:8080
    networks:
      - backend

  poker-api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - redis
    networks:
      - backend
    environment:
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    ports:
      - target: 8080
        published: 8080

  populate-redis:
    build:
      context: ../
      dockerfile: docker/Dockerfile-populate-redis
    depends_on:
      - redis
    networks:
      - backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1

  redis:
    image: redis
    ports:
      - target: 6379
        published: 6379
    networks:
      - backend
    volumes:
      - redis:/data

networks:
  backend:

volumes:
  redis: