apiVersion: v1
kind: Pod
metadata:
  name: poker-populate-redis
spec:
  containers:
  - name: poker-populate-redis
    image: carlschader/poker-populate-redis
    env:
    - name: REDIS_HOST
      value: redis.default.svc.cluster.local
    - name: REDIS_PORT
      value: "6379"
  restartPolicy: Never